name: Build & Create Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Install dependencies and build the executables
    - name: Install Dependencies and Build Executables
      run: |
        npm ci
        npm run build

    # Create a new release
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        body: |
          Created by a workflow.
        draft: false
        prerelease: false

    # Upload the executables to the release
    - name: Upload Executables
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dockerit-windows.exe
        asset_name: dockerit-windows.zip
        asset_content_type: application/zip
